#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

case "$1" in
    configure)

        db_version 2.0
        (
            cd /var/www/env/monero-wallet-service

            REREAD=`supervisorctl reread`
            supervisorctl update

            echo "Restarting uwsgi..."
            touch ./touch
            ./bin/python migration.py
            supervisorctl restart monero-wallet-service monero-wallet-service-api monero-wallet-service-pusher
        )
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac


db_stop
